### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [artemdolbiev/grid-template#5]
1)
заметные отличия во внешнем виде логотипа
![image](https://user-images.githubusercontent.com/8464662/84374854-516b4100-abe7-11ea-896f-f0bc5364d3a8.png)

2)
фокус на элементе реализован неправильно
![image](https://user-images.githubusercontent.com/8464662/84374942-752e8700-abe7-11ea-8977-4b73b92cbbbd.png)

3)
имя шаблона не подходящее, я бы рекомендовал переименовать )
![image](https://user-images.githubusercontent.com/8464662/84375100-b888f580-abe7-11ea-9497-313e896a6648.png)

**Comment by artemdolbiev** [comment]
Все ошибки выполнено

**Comment by Alecto** [comment]
скиньте пожалуйста ссылки, потому что в письме ничего для проверки нет.


[image: image.png]

чт, 11 черв. 2020 о 22:31 artemdolbiev <notifications@github.com> пише:
